# Change to summer operational mode
alias: Golvvärmereglering driftläge sommar
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.gvr_sommarlage_aktiv
    to: "on"
    for:
      hours: 0
      minutes: 2
      seconds: 0
condition:
  - condition: state
    entity_id: switch.gvr_automatiskt_driftlage
    state: "on"
action:
  - service: notify.mobile_app_my_iphone
    data:
      message: GVR driftläge sommar ({{ states('sensor.utetemperatur') }}).
mode: single

# Change to normal oprtational mode
alias: Golvvärmereglering driftläge normal
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.gvr_sommarlage_aktiv
    to: "off"
    for:
      hours: 0
      minutes: 2
      seconds: 0
condition:
  - condition: state
    entity_id: switch.gvr_automatiskt_driftlage
    state: "on"
action:
  - service: notify.mobile_app_my_iphone
    data:
      message: GVR driftläge normal ({{ states('sensor.utetemperatur') }}).
mode: single
