# Zone actuators modulation configuration

# Relay configuration
switch:
  # Zone 1 actuator relay
  - platform: gpio
    id: zone1_relay
    pin:
      number: GPIO16
      inverted: false
  # Zone 2 actuator relay
  - platform: gpio
    id: zone2_relay
    pin:
      number: GPIO17
      inverted: false
  # Zone 3 actuator relay
  - platform: gpio
    id: zone3_relay
    pin:
      number: GPIO18
      inverted: false
  # Zone 4 actuator relay
  - platform: gpio
    id: zone4_relay
    pin:
      number: GPIO19
      inverted: false
#  # Zone 5 actuator relay
#  - platform: gpio
#    id: zone5_relay
#    pin:
#      number: GPIO22
#      inverted: false
#  # Zone 6 actuator relay
#  - platform: gpio
#    id: zone6_relay
#    pin:
#      number: GPIO23
#      inverted: false
#  # Zone 7 actuator relay
#  - platform: gpio
#    id: zone7_relay
#    pin:
#      number: GPIO25
#      inverted: false
#  # Zone 8 actuator relay
#  - platform: gpio
#    id: zone8_relay
#    pin:
#      number: GPIO26
#      inverted: false

# Zone actuator configuration
output:
  # Zone 1 actuator
  - platform: sigma_delta_output
    update_interval: 6s
  #- platform: slow_pwm
  #  period: 10s
    id: zone1_modulation
    min_power: 0.20
    zero_means_zero: true
    turn_on_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state )
            id(zone1_relay).turn_on();
    turn_off_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state )
            id(zone1_relay).turn_off();
  # Zone 2 actuator
  - platform: sigma_delta_output
    update_interval: 6s
  #- platform: slow_pwm
  #  period: 10s
    id: zone2_modulation
    min_power: 0.20
    zero_means_zero: true
    turn_on_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state )
            id(zone2_relay).turn_on();
    turn_off_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state )
            id(zone2_relay).turn_off();
  # Zone 3 actuator
  - platform: sigma_delta_output
    update_interval: 6s
  #- platform: slow_pwm
  #  period: 10s
    id: zone3_modulation
    min_power: 0.20
    zero_means_zero: true
    turn_on_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state )
            id(zone3_relay).turn_on();
    turn_off_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state )
            id(zone3_relay).turn_off();
  # Zone 4 actuator
  - platform: sigma_delta_output
    update_interval: 6s
  #- platform: slow_pwm
  #  period: 10s
    id: zone4_modulation
    min_power: 0.20
    zero_means_zero: true
    turn_on_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state )
            id(zone4_relay).turn_on();
    turn_off_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state )
            id(zone4_relay).turn_off();
# Zone 5 actuator
#  #- platform: sigma_delta_output
#  #  update_interval: 6s
#  - platform: slow_pwm
#    period: 10s
#    id: zone5_modulation
#    min_power: 0.20
#    zero_means_zero: true
#    turn_on_action:
#      - lambda: |-
#          if ( id(${node_name}_controller_mode).state )
#            id(zone5_relay).turn_on();
#    turn_off_action:
#      - lambda: |-
#          if ( id(${node_name}_controller_mode).state )
#            id(zone5_relay).turn_off();
# Zone 6 actuator
#  #- platform: sigma_delta_output
#  #  update_interval: 6s
#  - platform: slow_pwm
#    period: 10s
#    id: zone6_modulation
#    min_power: 0.20
#    zero_means_zero: true
#    turn_on_action:
#      - lambda: |-
#          if ( id(${node_name}_controller_mode).state )
#            id(zone6_relay).turn_on();
#    turn_off_action:
#      - lambda: |-
#          if ( id(${node_name}_controller_mode).state )
#            id(zone6_relay).turn_off();
# Zone 7 actuator
#  #- platform: sigma_delta_output
#  #  update_interval: 6s
#  - platform: slow_pwm
#    period: 10s
#    id: zone7_modulation
#    min_power: 0.20
#    zero_means_zero: true
#    turn_on_action:
#      - lambda: |-
#          if ( id(${node_name}_controller_mode).state )
#            id(zone7_relay).turn_on();
#    turn_off_action:
#      - lambda: |-
#          if ( id(${node_name}_controller_mode).state )
#            id(zone7_relay).turn_off();
# Zone 8 actuator
#  #- platform: sigma_delta_output
#  #  update_interval: 6s
#  - platform: slow_pwm
#    period: 10s
#    id: zone8_modulation
#    min_power: 0.20
#    zero_means_zero: true
#    turn_on_action:
#      - lambda: |-
#          if ( id(${node_name}_controller_mode).state )
#            id(zone8_relay).turn_on();
#    turn_off_action:
#      - lambda: |-
#          if ( id(${node_name}_controller_mode).state )
#            id(zone8_relay).turn_off();

# Example how to link zones
#  # Link zone 5 actuator relay to zone 4
#    turn_on_action:
#      - output.turn_on: zone5_modulation
#    turn_off_action:
#      - output.turn_off: zone5_modulation
#  # Zone 5 actuator linked relay
#  - platform: gpio
#    id: zone5_modulation
#    pin:
#      number: GPIO22
#      inverted: false

# Thermostat configuration

# Zone temperature controller
#   Sampling time, Ts:      20 s (update interval of temperature sensor)
#   Critical gain, Kc:      18.0 (proportional constant causing oscillation)
#   Critical period, Pc:  4600 s (cycle time at oscillating condition)
# Calculated parameters  
#   Integral time, Ti:    2300 s (0.50 x Pc)
#   Derivative time, Td:   575 s (0.25 x Ti)
# Controller parameters
#   Proportional constant, kp:  10.8       (0.60 x Kc)
#   Integral constant, ki:       0.0004348 (1/Ti)
#   Derivative constant, kd:    28.8       (Td/Ts)

# Temperature controllers
climate:
  # Zone 1 temperature controller
  - platform: pid
    name: $zone1_name
    id: zone1_temperature_controller
    sensor: zone1_temperature
    default_target_temperature: 21.0°C
    heat_output: zone1_modulation
    control_parameters:
      kp: 10.8
      ki: 0.0004348
      kd: 28.8
      output_averaging_samples: 3
      derivative_averaging_samples: 5
#    deadband_parameters:
#      threshold_high: 0.4°C
#      threshold_low: -0.2°C
    visual:
      min_temperature: 17.0°C
      max_temperature: 25.0°C
      temperature_step: 0.1°C
  # Zone 2 temperature controller
  - platform: pid
    name: $zone2_name
    id: zone2_temperature_controller
    sensor: zone2_temperature
    default_target_temperature: 21.0°C
    heat_output: zone2_modulation
    control_parameters:
      kp: 10.8
      ki: 0.0004348
      kd: 28.8
      output_averaging_samples: 3
      derivative_averaging_samples: 5
#    deadband_parameters:
#      threshold_high: 0.4°C
#      threshold_low: -0.2°C
    visual:
      min_temperature: 17.0°C
      max_temperature: 25.0°C
      temperature_step: 0.1°C
  # Zone 3 temperature controller
  - platform: pid
    name: $zone3_name
    id: zone3_temperature_controller
    sensor: zone3_temperature
    default_target_temperature: 21.0°C
    heat_output: zone3_modulation
    control_parameters:
      kp: 10.8
      ki: 0.0004348
      kd: 28.8
      output_averaging_samples: 3
      derivative_averaging_samples: 5
#    deadband_parameters:
#      threshold_high: 0.4°C
#      threshold_low: -0.2°C
    visual:
      min_temperature: 17.0°C
      max_temperature: 25.0°C
      temperature_step: 0.1°C
  # Zone 4 temperature controller
  - platform: pid
    name: $zone4_name
    id: zone4_temperature_controller
    sensor: zone4_temperature
    default_target_temperature: 21.0°C
    heat_output: zone4_modulation
    control_parameters:
      kp: 10.8
      ki: 0.0004348
      kd: 28.8
      output_averaging_samples: 3
      derivative_averaging_samples: 5
#    deadband_parameters:
#      threshold_high: 0.4°C
#      threshold_low: -0.2°C
    visual:
      min_temperature: 17.0°C
      max_temperature: 25.0°C
      temperature_step: 0.1°C
#  # Zone 5 temperature controller
#  - platform: pid
#    name: $zone5_name
#    id: zone5_temperature_controller
#    sensor: zone5_temperature
#    default_target_temperature: 21.0°C
#    heat_output: zone5_modulation
#    control_parameters:
#      kp: 10.8
#      ki: 0.0004348
#      kd: 28.8
#      output_averaging_samples: 3
#      derivative_averaging_samples: 5
##    deadband_parameters:
##      threshold_high: 0.4°C
##      threshold_low: -0.2°C
#    visual:
#      min_temperature: 17.0°C
#      max_temperature: 25.0°C
#      temperature_step: 0.1°C
#  # Zone 6 temperature controller
#  - platform: pid
#    name: $zone6_name
#    id: zone6_temperature_controller
#    sensor: zone6_temperature
#    default_target_temperature: 21.0°C
#    heat_output: zone6_modulation
#    control_parameters:
#      kp: 10.8
#      ki: 0.0004348
#      kd: 28.8
#      output_averaging_samples: 3
#      derivative_averaging_samples: 5
##    deadband_parameters:
##      threshold_high: 0.4°C
##      threshold_low: -0.2°C
#    visual:
#      min_temperature: 17.0°C
#      max_temperature: 25.0°C
#      temperature_step: 0.1°C
#  # Zone 7 temperature controller
#  - platform: pid
#    name: $zone7_name
#    id: zone4_temperature_controller
#    sensor: zone4_temperature
#    default_target_temperature: 21.0°C
#    heat_output: zone4_modulation
#    control_parameters:
#      kp: 10.8
#      ki: 0.0004348
#      kd: 28.8
#      output_averaging_samples: 3
#      derivative_averaging_samples: 5
##    deadband_parameters:
##      threshold_high: 0.4°C
##      threshold_low: -0.2°C
#    visual:
#      min_temperature: 17.0°C
#      max_temperature: 25.0°C
#      temperature_step: 0.1°C
#  # Zone 8 temperature controller
#  - platform: pid
#    name: $zone8_name
#    id: zone4_temperature_controller
#    sensor: zone4_temperature
#    default_target_temperature: 21.0°C
#    heat_output: zone4_modulation
#    control_parameters:
#      kp: 10.8
#      ki: 0.0004348
#      kd: 28.8
#      output_averaging_samples: 3
#      derivative_averaging_samples: 5
##    deadband_parameters:
##      threshold_high: 0.4°C
##      threshold_low: -0.2°C
#    visual:
#      min_temperature: 17.0°C
#      max_temperature: 25.0°C
#      temperature_step: 0.1°C

# Actuator modulation level sensors
sensor:
  # Zone 1 actuator modulation level
  - platform: pid
    name: $zone1_name reglernivå
    id: zone1_modulation_level
    icon: mdi:chart-bell-curve-cumulative
    climate_id: zone1_temperature_controller
    type: HEAT
  # Zone 2 actuator modulation level
  - platform: pid
    name: $zone2_name reglernivå
    id: zone2_modulation_level
    icon: mdi:chart-bell-curve-cumulative
    climate_id: zone2_temperature_controller
    type: HEAT
  # Zone 3 actuator modulation level
  - platform: pid
    name: $zone3_name reglernivå
    id: zone3_modulation_level
    icon: mdi:chart-bell-curve-cumulative
    climate_id: zone3_temperature_controller
    type: HEAT
  # Zone 4 actuator modulation level
  - platform: pid
    name: $zone4_name reglernivå
    id: zone4_modulation_level
    icon: mdi:chart-bell-curve-cumulative
    climate_id: zone4_temperature_controller
    type: HEAT
#  # Zone 5 actuator modulation level
#  - platform: pid
#    name: $zone5_name reglernivå
#    id: zone5_modulation_level
#    icon: mdi:chart-bell-curve-cumulative
#    climate_id: zone5_temperature_controller
#    type: HEAT
#  # Zone 6 actuator modulation level
#  - platform: pid
#    name: $zone6_name reglernivå
#    id: zone6_modulation_level
#    icon: mdi:chart-bell-curve-cumulative
#    climate_id: zone6_temperature_controller
#    type: HEAT
#  # Zone 7 actuator modulation level
#  - platform: pid
#    name: $zone7_name reglernivå
#    id: zone7_modulation_level
#    icon: mdi:chart-bell-curve-cumulative
#    climate_id: zone7_temperature_controller
#    type: HEAT
#  # Zone 8 actuator modulation level
#  - platform: pid
#    name: $zone8_name reglernivå
#    id: zone8_modulation_level
#    icon: mdi:chart-bell-curve-cumulative
#    climate_id: zone8_temperature_controller
#    type: HEAT

# Zone valve actuator operational indicators
binary_sensor:
  # Zone 1 actuator
  - platform: template
    name: $zone1_name aktiv
    id: zone1_actuator_status
    icon: mdi:circle-slice-8
    filters:
      - delayed_on_off: 400ms
    lambda: |-
      if ( id(${node_name}_controller_mode).state ) {
        if ( id(zone1_modulation_level).state > 0 ) {
          return true;
        }
      } else {
        if ( id(zone1_manual_enable).state ) {
          return true;
        }
      }
      return false;
  # Zone 2 actuator
  - platform: template
    name: $zone2_name aktiv
    id: zone2_actuator_status
    icon: mdi:circle-slice-8
    filters:
      - delayed_on_off: 400ms
    lambda: |-
      if ( id(${node_name}_controller_mode).state ) {
        if ( id(zone2_modulation_level).state > 0 ) {
          return true;
        }
      } else {
        if ( id(zone2_manual_enable).state ) {
          return true;
        }
      }
      return false;
  # Zone 3 actuator
  - platform: template
    name: $zone3_name aktiv
    id: zone3_actuator_status
    icon: mdi:circle-slice-8
    filters:
      - delayed_on_off: 400ms
    lambda: |-
      if ( id(${node_name}_controller_mode).state ) {
        if ( id(zone3_modulation_level).state > 0 ) {
          return true;
        }
      } else {
        if ( id(zone3_manual_enable).state ) {
          return true;
        }
      }
      return false;
  # Zone 4 actuator
  - platform: template
    name: $zone4_name aktiv
    id: zone4_actuator_status
    icon: mdi:circle-slice-8
    filters:
      - delayed_on_off: 400ms
    lambda: |-
      if ( id(${node_name}_controller_mode).state ) {
        if ( id(zone4_modulation_level).state > 0 ) {
          return true;
        }
      } else {
        if ( id(zone4_manual_enable).state ) {
          return true;
        }
      }
      return false;
#  # Zone 5 actuator
#  - platform: template
#    name: $zone5_name aktiv
#    id: zone5_actuator_status
#    icon: mdi:circle-slice-8
#    filters:
#      - delayed_on_off: 400ms
#    lambda: |-
#      if ( id(${node_name}_controller_mode).state ) {
#        if ( id(zone5_modulation_level).state > 0 ) {
#          return true;
#        }
#      } else {
#        if ( id(zone5_manual_enable).state ) {
#          return true;
#        }
#      }
#      return false;
#  # Zone 6 actuator
#  - platform: template
#    name: $zone6_name aktiv
#    id: zone6_actuator_status
#    icon: mdi:circle-slice-8
#    filters:
#      - delayed_on_off: 400ms
#    lambda: |-
#      if ( id(${node_name}_controller_mode).state ) {
#        if ( id(zone6_modulation_level).state > 0 ) {
#          return true;
#        }
#      } else {
#        if ( id(zone6_manual_enable).state ) {
#          return true;
#        }
#      }
#      return false;
#  # Zone 7 actuator
#  - platform: template
#    name: $zone7_name aktiv
#    id: zone7_actuator_status
#    icon: mdi:circle-slice-8
#    filters:
#      - delayed_on_off: 400ms
#    lambda: |-
#      if ( id(${node_name}_controller_mode).state ) {
#        if ( id(zone7_modulation_level).state > 0 ) {
#          return true;
#        }
#      } else {
#        if ( id(zone7_manual_enable).state ) {
#          return true;
#        }
#      }
#      return false;
##  # Zone 8 actuator
#  - platform: template
#    name: $zone8_name aktiv
#    id: zone8_actuator_status
#    icon: mdi:circle-slice-8
#    filters:
#      - delayed_on_off: 400ms
#    lambda: |-
#      if ( id(${node_name}_controller_mode).state ) {
#        if ( id(zone8_modulation_level).state > 0 ) {
#          return true;
#        }
#      } else {
#        if ( id(zone8_manual_enable).state ) {
#          return true;
#        }
#      }
#      return false;
