#
# ESP32 SSR Floor Heating Controller
#
# https://github.com/jnasholm/fhc-pwm/tree/main
#
# Main configuration
#
substitutions:
  node_name: gvr
  node_prefix: GVR

# Define zone names
  zone1_name: Kök
  zone2_name: Hall
  zone3_name: Duschrum
  zone4_name: Vardagsrum
#  zone5_name: Arbetsrum
#  zone6_name: Barnrum
#  zone7_name: Sovrum
#  zone8_name: Teverum

# Project configuration
esphome:
  project:
    name: "jnasholm.fhc-pwm"
    version: "0.3"
  name: $node_name
  friendly_name: $node_prefix
  comment: Floor Heating Controller
  min_version: 2025.11.0

# Flash write interval
preferences:
  flash_write_interval: 20min

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret hass_api_key

# Enable OTA
ota:
  - platform: esphome
    password: !secret ota_password

# Node switches
switch:
  - platform: restart
    name: Starta om nod
#  - platform: shutdown
#    name: Stäng av nod

# Node uptime
sensor:
  - platform: uptime
    name: Drifttid
    icon: mdi:timer-outline
    update_interval: 60s

# Node connection status
binary_sensor:
  - platform: status
    name: Anslutning
    id: ${node_name}_connection_status
    icon: mdi:lan

# Include packages
packages:
  boardconfig: !include boardconfig.yaml
#  battery: !include battery.yaml
  time: !include time.yaml
  status: !include status.yaml
  controls: !include controls.yaml
#  homeassistant: !include sensors-homeassistant.yaml
  room_temp: !include sensors-room_temp.yaml
#  room_climate: !include sensors-room_climate.yaml
  outdoor_temp: !include sensors-outdoor_temp.yaml
  actuators: !include control-actuators.yaml
  circulation_pump: !include control-circulation_pump.yaml
