# Room temperature sensor configuration

# Digital floor heating zone temperature sensor bus configuration
#one_wire:
#  - platform: gpio
#    pin: $digital_room_temperature_pin
#    id: room_temperature_bus

# Broadcast provider configuration
#substitutions:
#  provider_zone1_node_name: rcs1
#  provider_zone2_node_name: rcs2
#  provider_zone3_node_name: rcs3
#  provider_zone4_node_name: rcs4
#  provider_zone5_node_name: rcs5
#  provider_zone6_node_name: rcs6
#  provider_zone7_node_name: rcs7
#  provider_zone8_node_name: rcs8

# Packet transport configuration
#udp:

#packet_transport:
#  - platform: udp
#    id: transport_input
#    providers:
#      - name: $provider_zone1_node_name
#        encryption: !secret broadcast_key
#      - name: $provider_zone2_node_name
#        encryption: !secret broadcast_key
#      - name: $provider_zone3_node_name
#        encryption: !secret broadcast_key
#      - name: $provider_zone4_node_name
#        encryption: !secret broadcast_key
#      - name: $provider_zone5_node_name
#        encryption: !secret broadcast_key
#      - name: $provider_zone6_node_name
#        encryption: !secret broadcast_key
#      - name: $provider_zone7_node_name
#        encryption: !secret broadcast_key
#      - name: $provider_zone8_node_name
#        encryption: !secret broadcast_key

# Remote floor heating zone temperature and humidity sensors (Home Assistant)
sensor:
  # Zone 1
  - platform: homeassistant
    name: $zone1_name temperatur
    id: zone1_temperature
    entity_id: sensor.zone1_temperature
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
#      - sliding_window_moving_average:
#          window_size: 3
#          send_every: 1
      - heartbeat: 10s
      - lambda: |-
          if ( id(${node_name}_connection_status).state )
            if ( !isnan(id(zone1_temperature).state) ) return x;
          return 20.0;
  - platform: homeassistant
    name: $zone1_name luftfuktighet
    id: zone1_humidity
    entity_id: sensor.zone1_humidity
    unit_of_measurement: '%'
    device_class: humidity
    state_class: measurement
    accuracy_decimals: 1
  # Zone 2
  - platform: homeassistant
    name: $zone2_name temperatur
    id: zone2_temperature
    entity_id: sensor.zone2_temperature
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
#      - sliding_window_moving_average:
#          window_size: 3
#          send_every: 1
      - heartbeat: 10s
      - lambda: |-
          if ( id(${node_name}_connection_status).state )
            if ( !isnan(id(zone2_temperature).state) ) return x;
          return 20.0;
  - platform: homeassistant
    name: $zone2_name luftfuktighet
    id: zone2_humidity
    entity_id: sensor.zone2_humidity
    unit_of_measurement: '%'
    device_class: humidity
    state_class: measurement
    accuracy_decimals: 1
  # Zone 3
  - platform: homeassistant
    name: $zone3_name temperatur
    id: zone3_temperature
    entity_id: sensor.zone3_temperature
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
#      - sliding_window_moving_average:
#          window_size: 3
#          send_every: 1
      - heartbeat: 10s
      - lambda: |-
          if ( id(${node_name}_connection_status).state )
            if ( !isnan(id(zone3_temperature).state) ) return x;
          return 20.0;
  - platform: homeassistant
    name: $zone3_name luftfuktighet
    id: zone3_humidity
    entity_id: sensor.zone3_humidity
    unit_of_measurement: '%'
    device_class: humidity
    state_class: measurement
    accuracy_decimals: 1
  # Zone 4
  - platform: homeassistant
    name: $zone4_name temperatur
    id: zone4_temperature
    entity_id: sensor.zone4_temperature
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
#      - sliding_window_moving_average:
#          window_size: 3
#          send_every: 1
      - heartbeat: 10s
      - lambda: |-
          if ( id(${node_name}_connection_status).state )
            if ( !isnan(id(zone4_temperature).state) ) return x;
          return 20.0;
  - platform: homeassistant
    name: $zone4_name luftfuktighet
    id: zone4_humidity
    entity_id: sensor.zone4_humidity
    unit_of_measurement: '%'
    device_class: humidity
    state_class: measurement
    accuracy_decimals: 1
#  # Zone 5
#  - platform: homeassistant
#    name: $zone5_name temperatur
#    id: zone5_temperature
#    entity_id: sensor.zone5_temperature
#    unit_of_measurement: °C
#    device_class: temperature
#    state_class: measurement
#    accuracy_decimals: 2
#    filters:
#      - sliding_window_moving_average:
#          window_size: 3
#          send_every: 1
#      - heartbeat: 10s
#      - lambda: |-
#          if ( id(${node_name}_connection_status).state )
#            if ( !isnan(id(zone5_temperature).state) ) return x;
#          return 20.0;
#  - platform: homeassistant
#    name: $zone5_name luftfuktighet
#    id: zone5_humidity
#    entity_id: sensor.zone5_humidity
#    unit_of_measurement: '%'
#    device_class: humidity
#    state_class: measurement
#    accuracy_decimals: 1
#  # Zone 6
#  - platform: homeassistant
#    name: $zone6_name temperatur
#    id: zone6_temperature
#    entity_id: sensor.zone6_temperature
#    unit_of_measurement: °C
#    device_class: temperature
#    state_class: measurement
#    accuracy_decimals: 2
#    filters:
#      - sliding_window_moving_average:
#          window_size: 3
#          send_every: 1
#      - heartbeat: 10s
#      - lambda: |-
#          if ( id(${node_name}_connection_status).state )
#            if ( !isnan(id(zone6_temperature).state) ) return x;
#          return 20.0;
#  - platform: homeassistant
#    name: $zone6_name luftfuktighet
#    id: zone6_humidity
#    entity_id: sensor.zone6_humidity
#    unit_of_measurement: '%'
#    device_class: humidity
#    state_class: measurement
#    accuracy_decimals: 1
#  # Zone 7
#  - platform: homeassistant
#    name: $zone7_name temperatur
#    id: zone7_temperature
#    entity_id: sensor.zone7_temperature
#    unit_of_measurement: °C
#    device_class: temperature
#    state_class: measurement
#    accuracy_decimals: 2
#    filters:
#      - sliding_window_moving_average:
#          window_size: 3
#          send_every: 1
#      - heartbeat: 10s
#      - lambda: |-
#          if ( id(${node_name}_connection_status).state )
#            if ( !isnan(id(zone7_temperature).state) ) return x;
#          return 20.0;
#  - platform: homeassistant
#    name: $zone7_name luftfuktighet
#    id: zone7_humidity
#    entity_id: sensor.zone7_humidity
#    unit_of_measurement: '%'
#    device_class: humidity
#    state_class: measurement
#    accuracy_decimals: 1
#  # Zone 8
#  - platform: homeassistant
#    name: $zone8_name temperatur
#    id: zone8_temperature
#    entity_id: sensor.zone8_temperature
#    unit_of_measurement: °C
#    device_class: temperature
#    state_class: measurement
#    accuracy_decimals: 2
#    filters:
#      - sliding_window_moving_average:
#          window_size: 3
#          send_every: 1
#      - heartbeat: 10s
#      - lambda: |-
#          if ( id(${node_name}_connection_status).state )
#            if ( !isnan(id(zone8_temperature).state) ) return x;
#          return 20.0;
#  - platform: homeassistant
#    name: $zone8_name luftfuktighet
#    id: zone8_humidity
#    entity_id: sensor.zone8_humidity
#    unit_of_measurement: '%'
#    device_class: humidity
#    state_class: measurement
#    accuracy_decimals: 1

# Remote floor heating zone temperature sensors (Broadcast)
#sensor:
#  - platform: packet_transport
#    id: zone1_temperature
#    transport_id: transport_input
#    provider: $provider_zone1_node_name
#    remote_id: zone_temperature
#    unit_of_measurement: °C
#    device_class: temperature
#    state_class: measurement
#    accuracy_decimals: 2
#    filters:
#      - heartbeat: 10s
#      - lambda: |-
#          if ( id(${node_name}_connection_status).state )
#            if ( !isnan(id(zone1_temperature).state) ) return x;
#          return 20.0;
#  - platform: packet_transport
#    id: zone2_temperature
#    transport_id: transport_input
#    provider: $provider_zone2_node_name
#    remote_id: zone_temperature
#    unit_of_measurement: °C
#    device_class: temperature
#    state_class: measurement
#    accuracy_decimals: 2
#    filters:
#      - heartbeat: 10s
#      - lambda: |-
#          if ( id(${node_name}_connection_status).state )
#            if ( !isnan(id(zone2_temperature).state) ) return x;
#          return 20.0;
#  - platform: packet_transport
#    id: zone3_temperature
#    transport_id: transport_input
#    provider: $provider_zone3_node_name
#    remote_id: zone_temperature
#    unit_of_measurement: °C
#    device_class: temperature
#    state_class: measurement
#    accuracy_decimals: 2
#    filters:
#      - heartbeat: 10s
#      - lambda: |-
#          if ( id(${node_name}_connection_status).state )
#            if ( !isnan(id(zone3_temperature).state) ) return x;
#          return 20.0;
#  - platform: packet_transport
#    id: zone4_temperature
#    transport_id: transport_input
#    provider: $provider_zone4_node_name
#    remote_id: zone_temperature
#    unit_of_measurement: °C
#    device_class: temperature
#    state_class: measurement
#    accuracy_decimals: 2
#    filters:
#      - heartbeat: 10s
#      - lambda: |-
#          if ( id(${node_name}_connection_status).state )
#            if ( !isnan(id(zone4_temperature).state) ) return x;
#          return 20.0;
#  - platform: packet_transport
#    id: zone5_temperature
#    transport_id: transport_input
#    provider: $provider_zone5_node_name
#    remote_id: zone_temperature
#    unit_of_measurement: °C
#    device_class: temperature
#    state_class: measurement
#    accuracy_decimals: 2
#    filters:
#      - heartbeat: 10s
#      - lambda: |-
#          if ( id(${node_name}_connection_status).state )
#            if ( !isnan(id(zone5_temperature).state) ) return x;
#          return 20.0;
#  - platform: packet_transport
#    id: zone6_temperature
#    transport_id: transport_input
#    provider: $provider_zone6_node_name
#    remote_id: zone_temperature
#    unit_of_measurement: °C
#    device_class: temperature
#    state_class: measurement
#    accuracy_decimals: 2
#    filters:
#      - heartbeat: 10s
#      - lambda: |-
#          if ( id(${node_name}_connection_status).state )
#            if ( !isnan(id(zone6_temperature).state) ) return x;
#          return 20.0;
#  - platform: packet_transport
#    id: zone7_temperature
#    transport_id: transport_input
#    provider: $provider_zone7_node_name
#    remote_id: zone_temperature
#    unit_of_measurement: °C
#    device_class: temperature
#    state_class: measurement
#    accuracy_decimals: 2
#    filters:
#      - heartbeat: 10s
#      - lambda: |-
#          if ( id(${node_name}_connection_status).state )
#            if ( !isnan(id(zone7_temperature).state) ) return x;
#          return 20.0;
#  - platform: packet_transport
#    id: zone8_temperature
#    transport_id: transport_input
#    provider: $provider_zone8_node_name
#    remote_id: zone_temperature
#    unit_of_measurement: °C
#    device_class: temperature
#    state_class: measurement
#    accuracy_decimals: 2
#    filters:
#      - heartbeat: 10s
#      - lambda: |-
#          if ( id(${node_name}_connection_status).state )
#            if ( !isnan(id(zone8_temperature).state) ) return x;
#          return 20.0;

#  Digital zone 1 temperature (DS18B20)
#  - platform: dallas_temp
#    name: $zone1_name temperatur
#    id: zone1_temperature
#    update_interval: 10s
#    one_wire_id: room_temperature_bus
#    address: 0x6C00000CA32B7B_S1
#    resolution: 12
#    accuracy_decimals: 2
#  Digital zone 2 temperature (DS18B20)
#  - platform: dallas_temp
#    name: $zone2_name temperatur
#    id: zone2_temperature
#    update_interval: 10s
#    one_wire_id: room_temperature_bus
#    address: 0x6C00000CA32B7B_S2
#    resolution: 12
#    accuracy_decimals: 2
#  Digital zone 3 temperature (DS18B20)
#  - platform: dallas_temp
#    name: $zone3_name temperatur
#    id: zone3_temperature
#    update_interval: 10s
#    one_wire_id: room_temperature_bus
#    address: 0x6C00000CA32B7B_S3
#    resolution: 12
#    accuracy_decimals: 2
#  Digital zone 4 temperature (DS18B20)
#  - platform: dallas_temp
#    name: $zone4_name temperatur
#    id: zone4_temperature
#    update_interval: 10s
#    one_wire_id: room_temperature_bus
#    address: 0x6C00000CA32B7B_S4
#    resolution: 12
#    accuracy_decimals: 2
#  Digital zone 5 temperature (DS18B20)
#  - platform: dallas_temp
#    name: $zone5_name temperatur
#    id: zone5_temperature
#    update_interval: 10s
#    one_wire_id: room_temperature_bus
#    address: 0x6C00000CA32B7B_S5
#    resolution: 12
#    accuracy_decimals: 2
#  Digital zone 6 temperature (DS18B20)
#  - platform: dallas_temp
#    name: $zone6_name temperatur
#    id: zone6_temperature
#    update_interval: 10s
#    one_wire_id: room_temperature_bus
#    address: 0x6C00000CA32B7B_S6
#    resolution: 12
#    accuracy_decimals: 2
#  Digital zone 7 temperature (DS18B20)
#  - platform: dallas_temp
#    name: $zone7_name temperatur
#    id: zone7_temperature
#    update_interval: 10s
#    one_wire_id: room_temperature_bus
#    address: 0x6C00000CA32B7B_S7
#    resolution: 12
#    accuracy_decimals: 2
#  Digital zone 8 temperature (DS18B20)
#  - platform: dallas_temp
#    name: $zone8_name temperatur
#    id: zone8_temperature
#    update_interval: 10s
#    one_wire_id: room_temperature_bus
#    address: 0x6C00000CA32B7B_S8
#    resolution: 12
#    accuracy_decimals: 2
