# Room temperature sensor configuration

# Input configuration room temperatures
dallas:
  - pin: GPIO13
    id: room_temperature_bus
    update_interval: 10s

# Zone 1 temperature
sensor:
  - platform: dallas
    name: $zone1_name temperatur
    id: zone1_temperature
    dallas_id: room_temperature_bus
    address: 0x6C00000CA32B7B_S1
    resolution: 12
# Zone 2 temperature
  - platform: dallas
    name: $zone2_name temperatur
    id: zone2_temperature
    dallas_id: room_temperature_bus
    address: 0x6C00000CA32B7B_S2
    resolution: 12
# Zone 3 temperature
  - platform: dallas
    name: $zone3_name temperatur
    id: zone3_temperature
    dallas_id: room_temperature_bus
    address: 0x6C00000CA32B7B_S3
    resolution: 12
# Zone 4 temperature
  - platform: dallas
    name: $zone4_name temperatur
    id: zone4_temperature
    dallas_id: room_temperature_bus
    address: 0x6C00000CA32B7B_S4
    resolution: 12
# Zone 5 temperature
#  - platform: dallas
#    name: $zone5_name temperatur
#    id: zone5_temperature
#    dallas_id: room_temperature_bus
#    address: 0x6C00000CA32B7B_S5
#    resolution: 12
# Zone 6 temperature
#  - platform: dallas
#    name: $zone6_name temperatur
#    id: zone6_temperature
#    dallas_id: room_temperature_bus
#    address: 0x6C00000CA32B7B_S6
#    resolution: 12
# Zone 7 temperature
#  - platform: dallas
#    name: $zone7_name temperatur
#    id: zone7_temperature
#    dallas_id: room_temperature_bus
#    address: 0x6C00000CA32B7B_S7
#    resolution: 12
# Zone 8 temperature
#  - platform: dallas
#    name: $zone8_name temperatur
#    id: zone8_temperature
#    dallas_id: room_temperature_bus
#    address: 0x6C00000CA32B7B_S8
#    resolution: 12
