# Room temperature sensor configuration

# Input configuration room temperatures
dallas:
  - pin: GPIO27
    update_interval: 10s

# Zone 1 temperature
sensor:
  - platform: dallas
    name: "$zone1_name temperatur"
    id: zone1_temperature
    address: 0x6C00000CA32B7B28
    resolution: 12
# Zone 2 temperature
  - platform: dallas
    name: "$zone2_name temperatur"
    id: zone2_temperature
    address: 0xEB00000CA3DFB328
    resolution: 12
# Zone 3 temperature
  - platform: dallas
    name: "$zone3_name temperatur"
    id: zone3_temperature
    address: 0xA300000CA437C528
    resolution: 12
# Zone 4 temperature
  - platform: dallas
    name: "$zone4_name temperatur"
    id: zone4_temperature
    address: 0x7400000CAE1E8328
    resolution: 12
