# Home Assistant configuration

# Floor heating zone temperatures
sensor:
  - platform: homeassistant
    name: $zone1_name temperatur
    id: zone1_temperature
    entity_id: sensor.zone1_temperature
    filters:
      - heartbeat: 10s
  - platform: homeassistant
    name: $zone2_name temperatur
    id: zone2_temperature
    entity_id: sensor.zone2_temperature
    filters:
      - heartbeat: 10s
  - platform: homeassistant
    name: $zone3_name temperatur
    id: zone3_temperature
    entity_id: sensor.zone3_temperature
    filters:
      - heartbeat: 10s
  - platform: homeassistant
    name: $zone4_name temperatur
    id: zone4_temperature
    entity_id: sensor.zone4_temperature
    filters:
      - heartbeat: 10s
# Outdoor temperature
  - platform: homeassistant
    name: $node_prefix utetemperatur
    id: outdoor_temperature
    entity_id: sensor.utetemperatur
    filters:
      - heartbeat: 10s
# Supply line temperature
  - platform: homeassistant
    name: $node_prefix tillopp
    id: ${node_name}_supply_line_temperature
    entity_id: sensor.gvc_tillopp
    filters:
      - heartbeat: 10s
